# Generated by Django 4.1.3 on 2022-11-12 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('public_key_base58', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_hash', models.CharField(max_length=255)),
                ('impressions_total', models.IntegerField(default=0)),
                ('likes_total', models.IntegerField(default=0)),
                ('diamonds_total', models.IntegerField(default=0)),
                ('comments_total', models.IntegerField(default=0)),
                ('reposts_total', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_hash', models.CharField(max_length=255)),
                ('source_app', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Diamond'), (2, 'Desofy'), (3, 'Entre')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('remote_addr', models.GenericIPAddressField(null=True, unpack_ipv4=True)),
                ('user_agent', models.CharField(max_length=255, null=True)),
                ('referer', models.CharField(max_length=255, null=True)),
                ('creator_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('device_family', models.CharField(max_length=255, null=True)),
                ('device_brand', models.CharField(max_length=255, null=True)),
                ('device_model', models.CharField(max_length=255, null=True)),
                ('browser_family', models.CharField(max_length=255, null=True)),
                ('browser_version', models.CharField(max_length=14, null=True)),
                ('os_family', models.CharField(max_length=255, null=True)),
                ('os_version', models.CharField(max_length=14, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('tz', models.CharField(max_length=255, null=True)),
                ('is_deso', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.post')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
