# Generated by Django 4.1.3 on 2022-11-13 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_post_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impression',
            name='post',
        ),
        migrations.RemoveField(
            model_name='impression',
            name='post_hash',
        ),
        migrations.AddField(
            model_name='impression',
            name='posts',
            field=models.ManyToManyField(blank=True, to='analytics.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.creator'),
        ),
        migrations.AlterField(
            model_name='post',
            name='node',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.node'),
        ),
    ]
