# Generated by Django 4.1.3 on 2022-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_impression_post_remove_impression_post_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_hash',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
