# Generated by Django 4.1.3 on 2022-12-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_creator_follower_creator_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='public_key_base58',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
