# Generated by Django 4.1.3 on 2022-12-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_creator_public_key_base58'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followers', to='analytics.creator'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followings', to='analytics.creator'),
        ),
    ]
