# Generated by Django 4.1.3 on 2022-12-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_creator_follower_alter_creator_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_bot_trigger',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creator',
            name='qualification',
            field=models.IntegerField(blank=True, choices=[(1, 'Bot'), (2, 'Irrelevant'), (3, 'Semi Relevant'), (4, 'Relevant'), (5, 'Celebrity')], default=1, null=True),
        ),
    ]
