# Generated by Django 4.1.3 on 2022-12-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_post_is_bot_trigger_alter_creator_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
