# Generated by Django 4.1.3 on 2022-12-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_creator_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_bot_processed',
            field=models.BooleanField(default=False),
        ),
    ]
