# Generated by Django 4.1.4 on 2022-12-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_post_is_bot_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='following',
        ),
        migrations.AddField(
            model_name='creator',
            name='coin_hodlers_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='coin_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='dao_holders_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='deso_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='cfollowers', to='analytics.creator'),
        ),
        migrations.AddField(
            model_name='creator',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='cfriends', to='analytics.creator'),
        ),
        migrations.AddField(
            model_name='creator',
            name='friends_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='hodlers',
            field=models.ManyToManyField(blank=True, related_name='chodlers', to='analytics.creator'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='qualification',
            field=models.IntegerField(blank=True, choices=[(1, 'Irrelevant'), (2, 'Semi Relevant'), (3, 'Relevant'), (4, 'Celebrity'), (5, 'Benign Bot'), (6, 'Malicious Bot')], default=1, null=True),
        ),
    ]
