# Generated by Django 4.1.4 on 2022-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_onchainapp_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sentiment_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
