# Generated by Django 4.1.4 on 2022-12-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_post_body_post_is_spam_alter_creator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='featured_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='profile_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onchainapp',
            name='app_store_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onchainapp',
            name='google_store_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onchainapp',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
