# Generated by Django 4.1.3 on 2022-11-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Impression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_hash", models.CharField(max_length=255)),
                (
                    "source_app",
                    models.IntegerField(
                        choices=[
                            (0, "Undefined"),
                            (1, "Diamond"),
                            (2, "Desofy"),
                            (3, "Entre"),
                        ],
                        default=0,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("referer", models.CharField(max_length=255, null=True)),
                (
                    "remote_addr",
                    models.GenericIPAddressField(null=True, unpack_ipv4=True),
                ),
                ("user_agent", models.CharField(max_length=255, null=True)),
                ("device_type", models.CharField(max_length=255, null=True)),
                ("browser_type", models.CharField(max_length=255, null=True)),
                ("browser_version", models.CharField(max_length=255, null=True)),
                ("os_type", models.CharField(max_length=255, null=True)),
                ("os_version", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=3, max_digits=5, null=True),
                ),
                ("tz", models.CharField(max_length=255, null=True)),
                ("is_deso", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
