# Generated by Django 4.1.3 on 2022-11-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impression', '0002_impression_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impression',
            old_name='browser_type',
            new_name='browser_family',
        ),
        migrations.RenameField(
            model_name='impression',
            old_name='device_type',
            new_name='device_brand',
        ),
        migrations.RenameField(
            model_name='impression',
            old_name='os_type',
            new_name='device_family',
        ),
        migrations.AddField(
            model_name='impression',
            name='creator_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='impression',
            name='device_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='impression',
            name='os_family',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='browser_version',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='is_deso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='impression',
            name='os_version',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
