# Generated by Django 4.1.3 on 2022-11-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_impression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_hash', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('impressions_total', models.IntegerField(default=0)),
                ('likes_total', models.IntegerField(default=0)),
                ('diamonds_total', models.IntegerField(default=0)),
                ('comments_total', models.IntegerField(default=0)),
                ('reposts_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='impression',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
            preserve_default=False,
        ),
    ]
